<template>
  <i :class="['icon', 'icon-' + name]" @click="$emit('click', $event)" />
</template>

<script>
export default {
  name: 'icon',

  props: {
    name: {
      type: String,
      required: true
    }
  }
};
</script>

<style>
@font-face {
  font-family: 'icon';
  src: url('icon-6b495bd63f.eot');
  src: url('icon-6b495bd63f.eot?#iefix') format('embedded-opentype'),
       url('icon-6b495bd63f.woff2') format('woff2'),
       url('icon-6b495bd63f.woff') format('woff'),
       url('icon-6b495bd63f.ttf') format('truetype')
}

.icon {
    display: inline-block;
}
.icon::before {
  font-family: "icon" !important;
  font-style: normal;
  font-weight: normal;
  speak: none;

  display: inline-block;
  text-decoration: inherit;
  width: 1em;
  text-align: center;

  /* For safety - reset parent styles, that can break glyph codes*/
  font-variant: normal;
  text-transform: none;

  /* fix buttons height, for twitter bootstrap */
  line-height: 1em;

  /* Animation center compensation - margins should be symmetric */
  /* remove if not needed */
  /* margin-left: .2em; */

  /* you can be more comfortable with increased icons size */
  /* font-size: 120%; */

  /* Font smoothing. That was taken from TWBS */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;

  /* Uncomment for 3D effect */
  /* text-shadow: 1px 1px 1px rgba(127, 127, 127, 0.3); */
}
/* DO NOT EDIT! Generated by iconfount */


.icon-qr-invalid:before { content: '\e800'; } /* '' */
.icon-qr:before { content: '\e801'; } /* '' */
.icon-exchange:before { content: '\e802'; } /* '' */
.icon-close:before { content: '\e803'; } /* '' */
.icon-location:before { content: '\e804'; } /* '' */
.icon-upgrade:before { content: '\e805'; } /* '' */
.icon-check:before { content: '\e806'; } /* '' */
.icon-checked:before { content: '\e807'; } /* '' */
.icon-like-o:before { content: '\e808'; } /* '' */
.icon-like:before { content: '\e809'; } /* '' */
.icon-chat:before { content: '\e80a'; } /* '' */
.icon-shop:before { content: '\e80b'; } /* '' */
.icon-photograph:before { content: '\e80c'; } /* '' */
.icon-add:before { content: '\e80d'; } /* '' */
.icon-add2:before { content: '\e80e'; } /* '' */
.icon-photo:before { content: '\e80f'; } /* '' */
.icon-logistics:before { content: '\e810'; } /* '' */
.icon-edit:before { content: '\e811'; } /* '' */
.icon-passed:before { content: '\e812'; } /* '' */
.icon-cart:before { content: '\e813'; } /* '' */
.icon-arrow:before { content: '\e814'; } /* '' */
.icon-gift:before { content: '\e815'; } /* '' */
.icon-search:before { content: '\e816'; } /* '' */
.icon-clear:before { content: '\e817'; } /* '' */
.icon-success:before { content: '\e818'; } /* '' */
.icon-fail:before { content: '\e819'; } /* '' */
.icon-contact:before { content: '\e81a'; } /* '' */
.icon-wechat:before { content: '\e81b'; } /* '' */
.icon-alipay:before { content: '\e81c'; } /* '' */
.icon-password-view:before { content: '\e81d'; } /* '' */
.icon-password-not-view:before { content: '\e81e'; } /* '' */
.icon-wap-nav:before { content: '\e81f'; } /* '' */
.icon-wap-home:before { content: '\e820'; } /* '' */
.icon-ecard-pay:before { content: '\e821'; } /* '' */
.icon-balance-pay:before { content: '\e822'; } /* '' */
.icon-peer-pay:before { content: '\e823'; } /* '' */
.icon-credit-pay:before { content: '\e824'; } /* '' */
.icon-debit-pay:before { content: '\e825'; } /* '' */
.icon-other-pay:before { content: '\e826'; } /* '' */
.icon-cart:before { content: '\e827'; } /* '' */
.icon-browsing-history:before { content: '\e828'; } /* '' */
.icon-goods-collect:before { content: '\e829'; } /* '' */
.icon-shop-collect:before { content: '\e82a'; } /* '' */
.icon-receive-gift:before { content: '\e82b'; } /* '' */
.icon-send-gift:before { content: '\e82c'; } /* '' */
.icon-setting:before { content: '\e82d'; } /* '' */
.icon-points:before { content: '\e82e'; } /* '' */
.icon-coupon:before { content: '\e82f'; } /* '' */
.icon-free-postage:before { content: '\e830'; } /* '' */
.icon-discount:before { content: '\e831'; } /* '' */
.icon-birthday-privilege:before { content: '\e832'; } /* '' */
.icon-member-day-privilege:before { content: '\e833'; } /* '' */
.icon-balance-details:before { content: '\e834'; } /* '' */
.icon-cash-back-record:before { content: '\e835'; } /* '' */
.icon-points-mall:before { content: '\e836'; } /* '' */
.icon-exchange-record:before { content: '\e837'; } /* '' */
.icon-pending-payment:before { content: '\e838'; } /* '' */
.icon-pending-orders:before { content: '\e839'; } /* '' */
.icon-pending-deliver:before { content: '\e83a'; } /* '' */
.icon-pending-evaluate:before { content: '\e83b'; } /* '' */
.icon-gift-card-pay:before { content: '\e83c'; } /* '' */
.icon-cash-on-deliver:before { content: '\e83d'; } /* '' */
.icon-underway:before { content: '\e83e'; } /* '' */
.icon-point-gift:before { content: '\e83f'; } /* '' */
.icon-after-sale:before { content: '\e840'; } /* '' */
.icon-edit-data:before { content: '\e841'; } /* '' */
.icon-question:before { content: '\e842'; } /* '' */
.icon-delete:before { content: '\e843'; } /* '' */
.icon-records:before { content: '\e844'; } /* '' */
.icon-description:before { content: '\e845'; } /* '' */
.icon-card:before { content: '\e846'; } /* '' */
.icon-gift-card:before { content: '\e847'; } /* '' */
.icon-coupon:before { content: '\e848'; } /* '' */
.icon-clock:before { content: '\e849'; } /* '' */
.icon-gold-coin:before { content: '\e84a'; } /* '' */
.icon-completed:before { content: '\e84b'; } /* '' */
.icon-value-card:before { content: '\e84c'; } /* '' */
</style>

